# Unified configuration for the entire dataset preparation pipeline.

# --- Stage 1: Download ---
download:
  csv_path: "asset/dataset.csv"
  source_dir: "dataset/raw"

# --- Stage 2: Preprocess ---
preprocess:
  output_dir: "dataset/processed"

# --- Stage 3: Align & Filter ---
align_and_filter:
  output_dir: "dataset/aligned"
  wp_std_threshold: 1.0

# --- Stage 4: Extract ---
extract:
  output_dir: "dataset/aligned"
  model_path: "checkpoints/extractor/latest.pth"
  config_path: "configs/extract_config.yaml"

# --- Stage 5: Tokenize ---
tokenize:
  output_dir: "dataset/tokenized"
  vocab_path: "./assets/vocab.json"
  save_format: "npy"
