# Configuration for the hFT-Transformer transcription pipeline.

# Path to the pre-trained model file.
model_path: "checkpoints/hft_transformer/latest.pkl"

# Path to the feature configuration file used by the model.
feature_config_path: "checkpoints/hft_transformer/config.json"

# Inference parameters
inference_params:
  mode: "combination"
  thred_mpe: 0.5
  thred_onset: 0.75
  thred_offset: 0.5
  n_stride: 32
  bpm: 120.0
